#!/usr/bin/env python3
import numpy as np
import pandas as pd
import os
import argparse
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import plotly.express as px
import plotly.io as pio
import demesdraw
import demes
from trasp import *
from mds import *
from utils import *
try:
    import msprime
except:
    print("cannot simulate")



from matplotlib.cm import get_cmap
from matplotlib import rcParams
def set_custom_rcparams():
    # -- Axes --
    rcParams['axes.spines.bottom'] = True
    rcParams['axes.spines.left'] = True
    rcParams['axes.spines.right'] = False
    rcParams['axes.spines.top'] = False
    rcParams['axes.grid'] = False
    rcParams['axes.grid.axis'] = 'y'
    rcParams['grid.color'] = 'black'
    rcParams['grid.linewidth'] = 0.5
    rcParams['axes.axisbelow'] = True
    rcParams['axes.linewidth'] = 1
    rcParams['axes.ymargin'] = 0
    # -- Ticks and tick labels --
    rcParams['axes.edgecolor'] = 'black'
    rcParams['xtick.color'] = 'black'
    rcParams['ytick.color'] = 'black'
    rcParams['xtick.major.width'] = 2
    rcParams['ytick.major.width'] = 0
    rcParams['xtick.major.size'] = 5
    rcParams['ytick.major.size'] = 0
    # -- Fonts --
    rcParams['font.size'] = 12
    rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Helvetica', 'Arial', 'sans-serif']
    rcParams['text.color'] = 'black'
    rcParams['axes.labelcolor'] = 'black'
    # -- Figure size --
    rcParams['figure.figsize'] = (6, 6)
    # -- Saving Options --
    rcParams['savefig.bbox'] = 'tight'
    rcParams['savefig.dpi'] = 500
    rcParams['savefig.transparent'] = False
    # -- Plot Styles --
    rcParams['lines.linewidth'] = 3
set_custom_rcparams()
def prepare_from_simulation(demes_file_path: str, n: int, L: int):
    """prepares an iterator of tree sequences given a demes file to simulate.

    Args:
        demes_file_path (str): The demography to be simulated in demes format
        n (int): number of haploid samples per population in given demography
        L (int): number of independent trees to simulate

    Returns:
        iterator: an iterator of tree sequences
        List[int]: a list of size L, where each entry is 2 (a single tree is taken from each simulation to ensure total independence)
        int: the total number of samples in the simulation
    """
    if "SS" in demes_file_path: ## simulate only 2 samples per deme for stepping stones models
        n=2
    graph = demes.load(demes_file_path)
    demography = msprime.Demography.from_demes(graph)
    K=0
    samples = {}
    population_samples_dict = {}
    for pop in demography.populations:
        if pop.default_sampling_time == 0:
            samples[pop.name] = n
            population_samples_dict[pop.name] = np.arange(n*K,n*(K+1))
            K+=1
    n_samples = n*K

    ts_list = msprime.sim_ancestry(
        samples = samples,
        demography = demography,
        sequence_length=1,
        ploidy = 1,
        num_replicates = L
        )

    L_list = [1]*L
    
    return ts_list,L_list,n_samples,population_samples_dict

def plot_deme(input,output,t_list,colors_dict,log_time):
    graph = demes.load(input)
    fig,ax_demes = plt.subplots(figsize = (3,5))
    demesdraw.tubes(graph,ax=ax_demes,max_time=np.max(t_list),colours = colors_dict,labels="xticks-legend",log_time=log_time)
    ax_demes.set_title("Simulated Demography")
    if ax_demes.get_legend() is not None:
        ax_demes.get_legend().remove()
    fig.savefig(os.path.join(output,"deme.png"),dpi=500)
    return fig

def dynamic_3d_plot(output, embeddings_df,colors_dict,log_time):
    component_1_df = embeddings_df[embeddings_df.component==1].drop(columns=["component","time_inx"])
    component_1_df.rename(columns={'embedding': 'dimension 1'}, inplace=True)
    component_2_df = embeddings_df[embeddings_df.component==2].drop(columns=["component","time_inx"])
    component_2_df.rename(columns={'embedding': 'dimension 2'}, inplace=True)
    df = pd.merge(component_1_df,component_2_df,how="right",on=["sample_id","population","time"])
    fig = px.line_3d(df, x="dimension 1", y="dimension 2", z="time",log_z=log_time, color='population',line_group='sample_id',
        color_discrete_map=colors_dict
    )
    fig.update_layout(showlegend=True)
    fig.show()
    pio.write_html(fig, file=os.path.join(output,"dynamic_3d_plot.html"))

    return fig

def plot_rate_trajectories(output, df, log_time):
    fig,ax = plt.subplots(1,1)
    df = df[df['sample_1_inx'] < df['sample_2_inx']]
    
    df['population_combination'] = df['population_1'].astype(str) + "_" + df['population_2'].astype(str)
    unique_pop_combs = np.unique(df['population_combination'])
    cmap = get_cmap("viridis")
    palette = [cmap(i / len(unique_pop_combs)) for i in range(len(unique_pop_combs))]
    color_dict = dict(zip(unique_pop_combs, palette))

    sample_1_inxs = np.unique(df["sample_1_inx"])
    sample_2_inxs = np.unique(df["sample_2_inx"])
    fig,ax = plt.subplots(1,1,figsize=(6,6))
    for sample_1_inx in sample_1_inxs:
        for sample_2_inx in sample_2_inxs:
                df_sub = df[(df["sample_1_inx"] == sample_1_inx) & (df["sample_2_inx"] == sample_2_inx)]
                if df_sub.shape[0] > 0:
                    ax.plot(df_sub["time"],df_sub["raw_rate"],lw=0.2,c = color_dict[df_sub["population_combination"].values[0]])
    if log_time:
        ax.set_xscale("log")

    handles = [plt.Line2D([0], [0], color=color_dict[pop], lw=2) for pop in unique_pop_combs]
    labels = unique_pop_combs
    ax.legend(handles, labels, title='Population Combination', loc='upper right')
    fig.savefig(os.path.join(output,"rate_trajectories.png"))
    return fig

def subset_metadata(metadata,populations = None,individuals_per_pop = None):
    if populations is None: # Select all populations
        populations = np.unique(metadata["population"])

    metadata_subset = metadata[metadata["population"].isin(populations)]
    if individuals_per_pop is not None:
        for population in populations:
            population_metadata = metadata_subset[metadata_subset['population']==population]
            n_samples_in_pop = len(population_metadata)
            if n_samples_in_pop < 2*individuals_per_pop: # If there are less than 2*individuals_per_pop samples in the population, select all samples
                continue 
            else:
                ind_ids = np.random.choice(np.arange(0, int(n_samples_in_pop/2)), size=individuals_per_pop, replace=False)
                haplotype_1_ids = 2*ind_ids
                haplotype_2_ids = 2*ind_ids+1
                subsample_ids = np.sort(np.concatenate([haplotype_1_ids,haplotype_2_ids]))
                subsample_ids = population_metadata.iloc[subsample_ids,:].sample_id.values
                drop_indices = population_metadata[~population_metadata["sample_id"].isin(subsample_ids)].index
                metadata_subset = metadata_subset.drop(drop_indices)
    metadata_subset = metadata_subset.reset_index(drop=True)
    return metadata_subset

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-input", type=str, required=True, help="path to directory with inferred trees")    
    parser.add_argument("-output", type=str, required=True, help="output path")
    parser.add_argument("-metadata", type=str, required = True, help="path to metadata file. Must include columns with names [population,sample_id]")
    parser.add_argument('-populations', type=str, default="", help="comma separated list of populations to subsample")
    parser.add_argument('-regions', type=str, default=None,help="comma separated list of regions to subsample")
    parser.add_argument('-n', type=int, default=None, help="number of individuals per population to subsample")
    parser.add_argument("-min_time", type=float, help="minimum time to start computing rates and embeddings")
    parser.add_argument("-max_time", type=float, help="maximum time to compute rates and embeddings")
    parser.add_argument("-num_timepoints", type=int, default=100, help="number of timepoints to use")
    parser.add_argument("-delta", type=float, help="the time width of each window")
    parser.add_argument("-log_time", action="store_true", help="use this flag to have log-spaced time points")

    args = parser.parse_args()
    
    input = args.input
    output = args.output
    metadata_path = args.metadata
    populations = args.populations
    regions = args.regions
    individuals_per_pop = args.n
    min_time = args.min_time
    max_time = args.max_time
    num_timepoints = args.num_timepoints
    delta = args.delta
    log_time = args.log_time

    os.makedirs(output,exist_ok=True)

    if log_time:
        t_list = np.logspace(np.log10(min_time),np.log10(max_time),num_timepoints)
    else:
        t_list = np.linspace(min_time,max_time,num_timepoints)

    # Subsampling populations
    metadata = pd.read_csv(metadata_path)

    if individuals_per_pop == 0:
        individuals_per_pop = None

    ## Subsampling by region
    if regions == "None" or regions is None:
        regions = None
        populations = populations.split(',')
    else:
        regions = regions.split(',')
        populations = np.unique(metadata[metadata.region.isin(regions)].population)
    
    ## Subsampling by population
    if populations[0] == "":
        if individuals_per_pop is None:
            metadata_subset = metadata
            sample_ids = None
        else:
            metadata_subset = subset_metadata(metadata,individuals_per_pop=individuals_per_pop)
            sample_ids = metadata_subset.sample_id.values
    else:
        metadata_subset = subset_metadata(metadata,populations,individuals_per_pop)
        sample_ids = metadata_subset.sample_id.values

    
    metadata_subset["sample_id"] = list(metadata_subset.index) # Resetting the sample ids after subsampling
    population_samples_dict = get_samples_dict(metadata_subset)
    metadata_subset.to_csv(f"{output}/metadata.csv",index=False)

    # Compute the rates
    print("Estimating pairwise coalescent rates")

    num_uncoalesced_through_time,num_coal_events_within_windows,rates_through_time = calculate_rates(input, t_list, delta, sample_ids)
    data_matrix = np.stack((num_uncoalesced_through_time,num_coal_events_within_windows,rates_through_time),axis=3)
    data_df = create_data_df(data_matrix,t_list,delta,population_samples_dict)

    # Compute the embeddings
    print("computing embeddings using MDS")
    embeddings_through_time = compute_embeddings_over_time(rates_through_time)
    embeddings_df = create_embeddings_df(embeddings_through_time,t_list,population_samples_dict)

    # Saving data
    data_df.write_parquet(os.path.join(output,"data.parquet"))
    embeddings_df.write_parquet(os.path.join(output,"embeddings.parquet"))

    # Plotting
    print("plotting results")
    embeddings_df = embeddings_df.to_pandas()
    labels = np.unique(embeddings_df.population)
    if "SS" in input:
        labels = np.array(sorted(labels, key=lambda x: int(x.split('_')[1])))
    K = len(labels)
    cmap = plt.get_cmap("rainbow")
    colors = cmap(np.linspace(0,255,K).astype(int))[:,:-1]
    colors_dict = {label:mcolors.to_hex(colors[i]) for i,label in enumerate(labels)}

    # if "SS" not in input and mode == "simulated":
    #     deme_fig = plot_deme(input,output,t_list,colors_dict,log_time)
    dynamic_fig = dynamic_3d_plot(output, embeddings_df, colors_dict, log_time)

    # Plotting the rates
    # data_df = data_df.to_pandas()
    # fig = plot_rate_trajectories(output, data_df, log_time)

if __name__ == "__main__":
    main()

# %%
